name: mc_server_info
version: 1.0.0
description: A Dart package for retrieving information about Minecraft servers.
repository: https://github.com/Abbas1Hussein/mc_server_info

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  udp: ^5.0.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.5
